# default: &default
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base:  asdlfjpun318rufu83ioew

test:
  secret_key_base:  jklfew8032i32jowef338j

staging:
  secret_key_base:  lij230873joijofw773jef

production:
  secret_key_base:  73hodfoiuohifwdoui8032
