require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DemosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Demo. As you add validations to Demo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DemosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all demos as @demos" do
      demo = Demo.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:demos)).to eq([demo])
    end
  end

  describe "GET #show" do
    it "assigns the requested demo as @demo" do
      demo = Demo.create! valid_attributes
      get :show, params: {id: demo.to_param}, session: valid_session
      expect(assigns(:demo)).to eq(demo)
    end
  end

  describe "GET #new" do
    it "assigns a new demo as @demo" do
      get :new, params: {}, session: valid_session
      expect(assigns(:demo)).to be_a_new(Demo)
    end
  end

  describe "GET #edit" do
    it "assigns the requested demo as @demo" do
      demo = Demo.create! valid_attributes
      get :edit, params: {id: demo.to_param}, session: valid_session
      expect(assigns(:demo)).to eq(demo)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Demo" do
        expect {
          post :create, params: {demo: valid_attributes}, session: valid_session
        }.to change(Demo, :count).by(1)
      end

      it "assigns a newly created demo as @demo" do
        post :create, params: {demo: valid_attributes}, session: valid_session
        expect(assigns(:demo)).to be_a(Demo)
        expect(assigns(:demo)).to be_persisted
      end

      it "redirects to the created demo" do
        post :create, params: {demo: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Demo.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved demo as @demo" do
        post :create, params: {demo: invalid_attributes}, session: valid_session
        expect(assigns(:demo)).to be_a_new(Demo)
      end

      it "re-renders the 'new' template" do
        post :create, params: {demo: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested demo" do
        demo = Demo.create! valid_attributes
        put :update, params: {id: demo.to_param, demo: new_attributes}, session: valid_session
        demo.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested demo as @demo" do
        demo = Demo.create! valid_attributes
        put :update, params: {id: demo.to_param, demo: valid_attributes}, session: valid_session
        expect(assigns(:demo)).to eq(demo)
      end

      it "redirects to the demo" do
        demo = Demo.create! valid_attributes
        put :update, params: {id: demo.to_param, demo: valid_attributes}, session: valid_session
        expect(response).to redirect_to(demo)
      end
    end

    context "with invalid params" do
      it "assigns the demo as @demo" do
        demo = Demo.create! valid_attributes
        put :update, params: {id: demo.to_param, demo: invalid_attributes}, session: valid_session
        expect(assigns(:demo)).to eq(demo)
      end

      it "re-renders the 'edit' template" do
        demo = Demo.create! valid_attributes
        put :update, params: {id: demo.to_param, demo: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested demo" do
      demo = Demo.create! valid_attributes
      expect {
        delete :destroy, params: {id: demo.to_param}, session: valid_session
      }.to change(Demo, :count).by(-1)
    end

    it "redirects to the demos list" do
      demo = Demo.create! valid_attributes
      delete :destroy, params: {id: demo.to_param}, session: valid_session
      expect(response).to redirect_to(demos_url)
    end
  end

end
